project:
  type: book
  output-dir: docs

book:
  title: "SLEIGH Documentation"
  author: "Michael R. Gallagher and Von P. Walden and Andrew S. Martin"
  date: "21 May 2023"
  date-format: "DD MMM YYYY"
  chapters:
    - index.md
    - getting-started.md
    - services.md
    - configuration.md
    - remote.md
    - manuals.md
    - data-summaries.md
    - santa.md

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    output-file: icecaps-melt-platform.pdf

format-links: [pdf]

